Enter -['1st']
['1st and 10 at WORCESTE35', 'WORCESTE ball on WORCESTE35, clock 15:00.']
['', 'Tyler Hapenny kickoff 49 yards to the WPI16, Zachary Levy return 7 yards to the WPI23 (Brenden Santos).']
Score correction made in Worcester St. @ WPI (index) quarter 3 drive 2
Is this opponent scout? (Y/N)Are you WPI (H) or Worcester St. (A)?Final score WPI 31 - Worcester St. 20
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at UNION35', 'UNION ball on UNION35, clock 15:00.']
['', 'Lau,Andrew kickoff 45 yards to the WSU20, Drew von Klock return 4 yards to the WSU24 (Vanderhoof,Jaco).']
Is this opponent scout? (Y/N)Are you Worcester St. (H) or Union (N.Y.) (A)?Final score Worcester St. 19 - Union (N.Y.) 56
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at FITCHBUR35', 'FITCHBUR ball on FITCHBUR35, clock 15:00.']
['', 'Mac Kimball kickoff 55 yards to the WORCESTE10, Brodie Jacques return 17 yards to the WORCESTE27 (Devin Current; Michael Brown).']
Is this opponent scout? (Y/N)Are you Worcester St. (H) or Fitchburg St. (A)?Final score Worcester St. 38 - Fitchburg St. 35
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at WSU35', 'UMass Dartmouth wins toss and will receive; WSU will defend South end-zone.']
['1st and 10 at WSU35', 'Start of 1st quarter, clock 15:00.']
['', 'Hapenny,Tyler kickoff 45 yards to the UMD20 Woodbury,Eric return 18 yards to the UMD38 (Broyles,Mason).']
Is this opponent scout? (Y/N)Are you Mass.-Dartmouth (H) or Worcester St. (A)?Final score Mass.-Dartmouth 52 - Worcester St. 7
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at BRIDGEWA35', 'BRIDGEWA ball on BRIDGEWA35, clock 15:00.']
['', 'Shane Drake kickoff 54 yards to the WORCESTE11, Brodie Jacques return 20 yards to the WORCESTE31 (Mitchell Gimble; Brandon Daley).']
Is this opponent scout? (Y/N)Are you Worcester St. (H) or Bridgewater St. (A)?Final score Worcester St. 13 - Bridgewater St. 49
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at WORCESTE35', 'MASS. MA ball on MASS. MA35, clock 15:00.']
['', 'George Lampros kickoff 65 yards to the WORCESTE00, touchback.']
Score correction made in Worcester St. @ Mass. Maritime (index) quarter 1 drive 6
Is this opponent scout? (Y/N)Are you Mass. Maritime (H) or Worcester St. (A)?Final score Mass. Maritime 24 - Worcester St. 28
Folder name? (Scout team name default)Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 97, in taster
    abbr = abbr_finder(quarters[0][drive_count],abbr)
IndexError: list index out of range
Enter -['1st']
['1st and 10 at WESTERN35', 'WESTERN ball on WESTERN35, clock 15:00.']
['1st and 10 at WESTERN35', 'Worcester State wins the toss, elects to receive']
['', 'A. Weidtman kickoff 60 yards to the WORCESTE05, Drew von Klock return 24 yards to the WORCESTE29 (Bryan Jones).']
Is this opponent scout? (Y/N)Are you Worcester St. (H) or Western Conn. St. (A)?Final score Worcester St. 30 - Western Conn. St. 56
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at WOR35', 'Westfield wins toss defers. Worcester to receive and defend north ez']
['1st and 10 at WOR35', 'WSU ball on WSU35.']
['1st and 10 at WSU35', 'PENALTY WSU of 5 yards to the WSU30.']
['1st and 15 at WSU30', 'WSU ball on WSU30.']
['', 'Julian, C. kickoff 48 yards to the WOR22, Drew von Klock return 5 yards to the WOR27 (Gardener, J.).']
Score correction made in Worcester St. @ Westfield St. (index) quarter 2 drive 2
Score correction made in Worcester St. @ Westfield St. (index) quarter 2 drive 5
Score correction made in Worcester St. @ Westfield St. (index) quarter 3 drive 0
Score correction made in Worcester St. @ Westfield St. (index) quarter 3 drive 1
Score correction made in Worcester St. @ Westfield St. (index) quarter 3 drive 2
Score correction made in Worcester St. @ Westfield St. (index) quarter 3 drive 5
Is this opponent scout? (Y/N)Are you Westfield St. (H) or Worcester St. (A)?Final score Westfield St. 30 - Worcester St. 33
Folder name? (Scout team name default)Enter -['1st']
['1st and 10 at FRAMINGH35', 'FRAMINGH ball on FRAMINGH35, clock 15:00.']
['1st and 10 at FRAMINGH35', 'Framingham Won Toss, Defers']
['', 'Henrique De Boni kickoff 65 yards to the WORCESTE00, touchback.']
Is this opponent scout? (Y/N)Are you Worcester St. (H) or Framingham St. (A)?Final score Worcester St. 21 - Framingham St. 40
Folder name? (Scout team name default)Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 17, in taster
    name_dict[away_name] = team_names[0].string
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
Enter -Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 10, in <module>
    quarters, name_dict = pbp_parser(url)
  File "C:\Users\surma\Python\cfb_slapPY\pbp_parser_func.py", line 21, in pbp_parser
    name_dict[home_name] = drive_chart('a', href='#home-drives')[0].string
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surma\Python\cfb_slapPY\sauce.py", line 13, in <module>
    quarters, name_dict = taster(url)  
  File "C:\Users\surma\Python\cfb_slapPY\taster_func.py", line 44, in taster
    name_dict[away_kicker] = kicker_names[0][0]
IndexError: list index out of range
